// SPDX-License-Identifier: MIT
// (c) Meta Platforms, Inc. and affiliates.

module sondos_axi_crossbar_wrapper
(
  so_axi4_if.slave axi_full_client_0,
  so_axi4_if.slave axi_full_client_1,
  so_axi4_if.slave axi_full_client_2,
  so_axi4_if.master axi_full_to_host
);

sondos_axi_crossbar  axi_crossbar_inst(
  .aclk(axi_full_to_host.aclk),
  .aresetn(axi_full_to_host.aresetn),
  .s_axi_awid     ({axi_full_client_2.awid   ,axi_full_client_1.awid   ,axi_full_client_0.awid}),
  .s_axi_awaddr   ({axi_full_client_2.awaddr ,axi_full_client_1.awaddr ,axi_full_client_0.awaddr}),
  .s_axi_awlen    ({axi_full_client_2.awlen  ,axi_full_client_1.awlen  ,axi_full_client_0.awlen}),
  .s_axi_awsize   ({axi_full_client_2.awsize ,axi_full_client_1.awsize ,axi_full_client_0.awsize}),
  .s_axi_awburst  ({axi_full_client_2.awburst,axi_full_client_1.awburst,axi_full_client_0.awburst}),
  .s_axi_awlock   ({axi_full_client_2.awlock ,axi_full_client_1.awlock ,axi_full_client_0.awlock}),
  .s_axi_awcache  ({axi_full_client_2.awcache,axi_full_client_1.awcache,axi_full_client_0.awcache}),
  .s_axi_awprot   ({axi_full_client_2.awprot ,axi_full_client_1.awprot ,axi_full_client_0.awprot}),
  .s_axi_awqos    ({axi_full_client_2.awqos  ,axi_full_client_1.awqos  ,axi_full_client_0.awqos}),
  .s_axi_awvalid  ({axi_full_client_2.awvalid,axi_full_client_1.awvalid,axi_full_client_0.awvalid}),
  .s_axi_awready  ({axi_full_client_2.awready,axi_full_client_1.awready,axi_full_client_0.awready}),
  .s_axi_wdata    ({axi_full_client_2.wdata  ,axi_full_client_1.wdata  ,axi_full_client_0.wdata}),
  .s_axi_wstrb    ({axi_full_client_2.wstrb  ,axi_full_client_1.wstrb  ,axi_full_client_0.wstrb}),
  .s_axi_wlast    ({axi_full_client_2.wlast  ,axi_full_client_1.wlast  ,axi_full_client_0.wlast}),
  .s_axi_wvalid   ({axi_full_client_2.wvalid ,axi_full_client_1.wvalid ,axi_full_client_0.wvalid}),
  .s_axi_wready   ({axi_full_client_2.wready ,axi_full_client_1.wready ,axi_full_client_0.wready}),
  .s_axi_bid      ({axi_full_client_2.bid    ,axi_full_client_1.bid    ,axi_full_client_0.bid}),
  .s_axi_bresp    ({axi_full_client_2.bresp  ,axi_full_client_1.bresp  ,axi_full_client_0.bresp}),
  .s_axi_bvalid   ({axi_full_client_2.bvalid ,axi_full_client_1.bvalid ,axi_full_client_0.bvalid}),
  .s_axi_bready   ({axi_full_client_2.bready ,axi_full_client_1.bready ,axi_full_client_0.bready}),
  .s_axi_arid     ({axi_full_client_2.arid   ,axi_full_client_1.arid   ,axi_full_client_0.arid}),
  .s_axi_araddr   ({axi_full_client_2.araddr ,axi_full_client_1.araddr ,axi_full_client_0.araddr}),
  .s_axi_arlen    ({axi_full_client_2.arlen  ,axi_full_client_1.arlen  ,axi_full_client_0.arlen}),
  .s_axi_arsize   ({axi_full_client_2.arsize ,axi_full_client_1.arsize ,axi_full_client_0.arsize}),
  .s_axi_arburst  ({axi_full_client_2.arburst,axi_full_client_1.arburst,axi_full_client_0.arburst}),
  .s_axi_arlock   ({axi_full_client_2.arlock ,axi_full_client_1.arlock ,axi_full_client_0.arlock}),
  .s_axi_arcache  ({axi_full_client_2.arcache,axi_full_client_1.arcache,axi_full_client_0.arcache}),
  .s_axi_arprot   ({axi_full_client_2.arprot ,axi_full_client_1.arprot ,axi_full_client_0.arprot}),
  .s_axi_arqos    ({axi_full_client_2.arqos  ,axi_full_client_1.arqos  ,axi_full_client_0.arqos}),
  .s_axi_arvalid  ({axi_full_client_2.arvalid,axi_full_client_1.arvalid,axi_full_client_0.arvalid}),
  .s_axi_arready  ({axi_full_client_2.arready,axi_full_client_1.arready,axi_full_client_0.arready}),
  .s_axi_rid      ({axi_full_client_2.rid    ,axi_full_client_1.rid    ,axi_full_client_0.rid}),
  .s_axi_rdata    ({axi_full_client_2.rdata  ,axi_full_client_1.rdata  ,axi_full_client_0.rdata}),
  .s_axi_rresp    ({axi_full_client_2.rresp  ,axi_full_client_1.rresp  ,axi_full_client_0.rresp}),
  .s_axi_rlast    ({axi_full_client_2.rlast  ,axi_full_client_1.rlast  ,axi_full_client_0.rlast}),
  .s_axi_rvalid   ({axi_full_client_2.rvalid ,axi_full_client_1.rvalid ,axi_full_client_0.rvalid}),
  .s_axi_rready   ({axi_full_client_2.rready ,axi_full_client_1.rready ,axi_full_client_0.rready}),
  .m_axi_awid(axi_full_to_host.awid),
  .m_axi_awaddr(axi_full_to_host.awaddr),
  .m_axi_awlen(axi_full_to_host.awlen),
  .m_axi_awsize(axi_full_to_host.awsize),
  .m_axi_awburst(axi_full_to_host.awburst),
  .m_axi_awlock(axi_full_to_host.awlock),
  .m_axi_awcache(axi_full_to_host.awcache),
  .m_axi_awprot(axi_full_to_host.awprot),
  .m_axi_awregion(axi_full_to_host.awregion),
  .m_axi_awqos(axi_full_to_host.awqos),
  .m_axi_awvalid(axi_full_to_host.awvalid),
  .m_axi_awready(axi_full_to_host.awready),
  .m_axi_wdata(axi_full_to_host.wdata),
  .m_axi_wstrb(axi_full_to_host.wstrb),
  .m_axi_wlast(axi_full_to_host.wlast),
  .m_axi_wvalid(axi_full_to_host.wvalid),
  .m_axi_wready(axi_full_to_host.wready),
  .m_axi_bid(axi_full_to_host.bid),
  .m_axi_bresp(axi_full_to_host.bresp),
  .m_axi_bvalid(axi_full_to_host.bvalid),
  .m_axi_bready(axi_full_to_host.bready),
  .m_axi_arid(axi_full_to_host.arid),
  .m_axi_araddr(axi_full_to_host.araddr),
  .m_axi_arlen(axi_full_to_host.arlen),
  .m_axi_arsize(axi_full_to_host.arsize),
  .m_axi_arburst(axi_full_to_host.arburst),
  .m_axi_arlock(axi_full_to_host.arlock),
  .m_axi_arcache(axi_full_to_host.arcache),
  .m_axi_arprot(axi_full_to_host.arprot),
  .m_axi_arregion(axi_full_to_host.arregion),
  .m_axi_arqos(axi_full_to_host.arqos),
  .m_axi_arvalid(axi_full_to_host.arvalid),
  .m_axi_arready(axi_full_to_host.arready),
  .m_axi_rid(axi_full_to_host.rid),
  .m_axi_rdata(axi_full_to_host.rdata),
  .m_axi_rresp(axi_full_to_host.rresp),
  .m_axi_rlast(axi_full_to_host.rlast),
  .m_axi_rvalid(axi_full_to_host.rvalid),
  .m_axi_rready(axi_full_to_host.rready)
);

endmodule
